### ISSUE TITLE
Why not provide the css for the dark mode?

### ISSUE THREAD

**Issue by kaiomagalhaes** [8bitgentleman/roam-depo-dark-toggle#1]
When I saw this extension on Roam I got myself wondering, why not offer the CSS for the dark mode as well? Is it a technical limitation of extensions?

**Comment by 8bitgentleman** [comment]
Not a technical limitation just not originally what I envisioned the extension was for. I made it to work with any CSS theme that has a dark/light mode but since release I have been considering bundling a very basic dark theme as an option

**Comment by weltonrodrigo** [comment]
Please do.

**Comment by 1551255004** [comment]
> Please do.

I also need it.

**Comment by 8bitgentleman** [comment]
How's something simple like this work for yall?

https://user-images.githubusercontent.com/4028391/207474003-8deb67e4-f367-4b70-914d-c3fe363ebfbb.mp4

**Comment by weltonrodrigo** [comment]
> How's something simple like this work for yall?
> 
>  Kapture.2022-12-13.at.19.23.56.mp4

Where can I find the CSS used in this video?

**Comment by 8bitgentleman** [comment]
> Where can I find the CSS used in this video?

It is not available yet. If this is what people are looking for I will merge it into the roam depot plugin

**Comment by 8bitgentleman** [comment]
This is now available as a setting toggle in the latest version of the extension
