### ISSUE TITLE
Toggle does not work

### ISSUE THREAD

**Issue by ksap1** [8bitgentleman/roam-depo-dark-toggle#4]
The toggle does nothing when clicked on on the mac app nor the chrome version.

**Comment by 8bitgentleman** [comment]
Out of the box this toggle does not do much and it mainly meant to facilitate dark modes in your own custom themes. Take a looks at the instructions [here](https://github.com/8bitgentleman/roam-depo-dark-toggle#css-dark-mode-toggle) for how to use it. There is an option in the settings to use a basic dark mode if you do not have your own theme. I will be expanding the basic dark mode soon for better support
